version: "3.9"

services:
  server:
      build: ./server
      ports:
        - "8000:8000"
      environment:
        - TEST_IMPORT=${TEST_IMPORT}
        - PROXY_API_KEY=${PROXY_API_KEY}
        - PROXY_BASE_URL=${PROXY_BASE_URL}
        - PROXY_MODEL=${PROXY_MODEL:-gpt-4o-mini}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PORT=${POSTGRES_PORT}
        - DATABASE_URL=${DATABASE_URL}
        - SPREADSHEET_ID=${SPREADSHEET_ID}
        - SERVICE_ACCOUNT_FILE=${SERVICE_ACCOUNT_FILE}
        - SERVER_URL=${SERVER_URL}
        - BOT_API_URL=${BOT_API_URL:-http://bot:5000}
        - LOG_LEVEL=${LOG_LEVEL:-INFO}
      volumes:
        - ./server:/app
        - ./templates:/templates
      depends_on:
        - postgres
      restart: unless-stopped

  bot:
      build: ./bot
      ports:
        - 5000:5000
      environment:
        - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
        - SERVER_URL=http://server:8000
      volumes:
        - ./bot:/app
        - ./templates:/app/templates:ro
      depends_on:
        - server
      restart: unless-stopped 

  postgres:
    image: postgres:16
    container_name: mentormatch-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: mentormatch-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin


volumes:
  pgdata:
  pgadmin_data:
